### ISSUE TITLE
Unsupported section magic: 'AGRP'

### ISSUE THREAD

**Issue by RibShark** [panzi/cook-serve-hoomans#1]
I am trying to extract the texture and sounds from a certain GameMaker game, and I have found a bit of a problem. This game seems to have a chunk not defined in your extractor. The section is actually, at least in this game, zeroed out (except for the chunk magic and content size of course). With this chunk included, the program refuses to extract any files from the game, but if I rename the chunk magic temporarily to something like OBJT for example, it extracts fine, probably meaning all that is required is simply adding the definition to the program.

The error is as follows:

`Reading archive...
*** ERROR: at offset 11340: unsupported section magic: 'AGRP' (0x41 0x47 0x52 0x50)
data.win: Function not implemented`

**Comment by panzi** [comment]
Thanks for the info. I just added that chunk magic.
